### ISSUE TITLE
Nothing is printed by the plugin

### ISSUE THREAD

**Issue by ilyaigpetrov** [coredns/example#15]
```sh-session
$ git clone https://github.com/coredns/coredns.git
$ cd coredns/plugin
$ git clone https://github.com/coredns/example
$ cd ..
$ vim plugin.cfg
# Comments here.
log:log
example:example
# Nothing else in this file.
$ make
$ vim ./Corefile
. {
  example
}
$ ./coredns -dns.port 1337
# In another terminal:
$ dig @127.0.0.1 -p 1337 example.com
# Expected: "example" must be printed in the `./coredns` output.
# Actually: 
$ ./coredns -dns.port 1337 
.:1337
CoreDNS-1.7.0
linux/amd64, go1.14.3, 8c6d016a-dirty
```

**Comment by chrisohaver** [comment]
There needs to be a plugin that can answer the query in the plugin chain after example.  once an answer is generated, example plugin prints "example" just before sending the answer to the client.

If you included the errors plugin, you'd see a "no next plugin" error, meaning that the example plugin tried passing the query to the next plugin, but there isn't one.

explained in this comment...
```
func (e Example) ServeDNS(ctx context.Context, w dns.ResponseWriter, r *dns.Msg) (int, error) {
	// This function could be simpler. I.e. just fmt.Println("example") here, but we want to show
	// a slightly more complex example as to make this more interesting.
	// Here we wrap the dns.ResponseWriter in a new ResponseWriter and call the next plugin, when the
	// answer comes back, it will print "example".
```

**Comment by ilyaigpetrov** [comment]
Thank you for your solution -- if I add `forward` plugin then it works as expected (prints "example" to output).
```sh-session
$ cat plugin.cfg
errors:errors
log:log
example:example
forward:forward
$ cat Corefile
example.com {
  forward . 9.9.9.9
  example
}
```
You've mentioned that `errors` plugin could be useful here so I decided to try it and tested the following configuration:
```sh-session
$ cat plugin.cfg
errors:errors
log:log
example:example
$ cat Corefile
example.com {
  example
}
$ make && ./coredns -dns.port 1337
(another terminal)$ dig @127.0.0.1 -p 1337 example.com
# Expected: "no next plugin" error must appear in the coredns output.
# Actual: no error message is printed to the output.
```
As you can see no error message is printed. Could you, please, advise me how to use `errors` plugin in this situation. This is not important so feel free to close this issues without answering my second question.

**Comment by ilyaigpetrov** [comment]
I forgot to add `errors` to the Corefile. Everything now works as expected. Thank you!

**Comment by chrisohaver** [comment]
> As you can see no error message is printed. Could you, please, advise me how to use errors plugin in this situation. 

Need to put it in the corefile too...
