### ISSUE TITLE
deploys fails 

### ISSUE THREAD

**Issue by peiqi-caicloud** [coredns/example#6]
I try to deploy coredns in my k8s 1.9 using your example configs.

no matter I remove serviceaccountname or not, it causes the same error: is this coded in your code in this version or did I do something wrong ?

2018/04/27 03:37:48 plugin/kubernetes: open /var/run/secrets/kubernetes.io/serviceaccount/token: no such file or directory

**Comment by peiqi-caicloud** [comment]
@caniszczyk

**Comment by miekg** [comment]
should probably have filled this under coredns.io/deployment instead of here...

/cc @chrisohaver

**Comment by miekg** [comment]
you can also ask on slack or the other channels listed on https://coredns.io/community/. Closing here.
